bill=float(input("Welcome to the tip calculator!\nWhat was the total bill:"))
tip=float(input("What percentage tip would you like to give? 0, 10, 12, or 15:"))
people=int(input("How many people to split the bill:"))
res=round((bill*((tip+100)/100))/people,2)
print("Each person should pay:{:.2f}".format(res))